### ISSUE TITLE
Status of 1.0?

### ISSUE THREAD

**Issue by duro** [middyjs/middy#309]
Hi there super rad maintainers of middy! Thank you all for your dedication to such a great library for serverless dev.

I was wondering if any of you might be able to comment on the readiness of the alpha builds of 1.0? We are in super early stages of a micro service migration to lambda, and I'm curious if it would better for us to build our POC around 1.0? Or if it still has too many rough edges that we are better off working against the pre-1.0 build?

I'm most curious becuase this POC is also going to be evaluated heavily for performance, and I know there are some improvements in 1.0 that are in the works.

I ask this only out of curiosity, and with no rush.

**Comment by vladgolubev** [comment]
I'd say build the PoC around 1.x. According to  https://github.com/middyjs/middy/milestone/2 no major API changes are planned

**Comment by lmammino** [comment]
Hello (again 😀) @duro!

Not sure yet when v1.0 will be officially released (replacing current 0.x). We are kind of [struggling a little bit](https://github.com/middyjs/middy/issues/263) to find some good amount of time to finish the [expected features](https://github.com/middyjs/middy/milestone/2) and we are mostly relying on external contributors for those.

With that being said, I'd say current v1.0.0-alpha-x (check out the [dedicated branch](https://github.com/middyjs/middy/tree/1.0.0-alpha)) is quite stable and, if you are building something new, I'd recommend using that.

As per major changes (from 0.x):
 - [http-header-normalizer](https://github.com/middyjs/middy/tree/1.0.0-alpha/packages/http-header-normalizer), now will normalize to lower case headers (as per any other major Node.js HTTP framework). Every core middleware in v1 has been adapted to this, so only the custom code would be affected.
- Modular infrastructure. Very small [core module](https://www.npmjs.com/package/@middy/core) and all other modules installable from NPM only if needed (this helps with speeding up lambda bootstrap time).

**Comment by duro** [comment]
@lmammino I'm going to start integrating 1.0. Also, let me know if there is any way I can help with the effort.

**Comment by duro** [comment]
@lmammino One thing I noticed with 1.0 is that the type definitions in Core do not include the same types as pre-1.0. What's the plan (or need) there?

**Comment by lmammino** [comment]
Thanks @duro, any help is most welcome where you see fit, especially if on the outstanding features expected for v1.

Regarding type definitions, they were moved into their own independent packages. Did you see any other difference? It could be possible that something is not aligned between the two branches.

**Comment by shroomist** [comment]
I find types on 0.23 being much more strictly defined with generics.
`v1.0.0-alpha` `middy()` function on the other hand returns simple `middy.IMiddy`
which in contrast does not tell much about ins and outs of my handler.

I wasn't able to build with 1.0.0-alpha
```ts
import * as middy from '@middy/core';
middy.middy(lambdaHandler)
```
yelds
`TypeError: middy.middy is not a function`
😢

**Comment by kevinswarner** [comment]
If I wanted to start using v1.0.0-alpha what is the best way to install with yarn? When I attempted to install as follows I get the following error...

```
> yarn add https://github.com/middyjs/middy.git#1.0.0-alpha
yarn add v1.15.2
warning package.json: No license field
warning @logicbox-llc/logicbox-lib-lambda-middleware@0.1.2: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/kevinwarner/Documents/Projects/logicbox/libs/lambda-middleware/node_modules/middy-monorepo: Command failed.
Exit code: 127
Command: lerna bootstrap
Arguments:
Directory: /Users/kevinwarner/Documents/Projects/logicbox/libs/lambda-middleware/node_modules/middy-monorepo
Output:
/bin/sh: lerna: command not found
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
kevinwarner ~/Documents/Projects/logicbox/libs/lambda-middleware (refactor) $
```
Is there something else or a different way I need to install?

Thanks.

**Comment by vladgolubev** [comment]
@kevinswarner it's already on npm, so smth like `yarn add middy@1.0.0-alpha` would work

**Comment by willfarrell** [comment]
`beta` will be out very soon. #457
