### ISSUE TITLE
middy-autoproxyresponse: next is not a function

### ISSUE THREAD

**Issue by serverlesspolska** [middyjs/middy#681]
Hello,

First I just want to say that **middy** is a great project!

I have an issue, after upgrading from middy 1.5 to 2.2 `middy-autoproxyresponse` plugin stopped working.

It throws error:
```
ERROR   TypeError: next is not a function
    at after (/var/task/node_modules/middy-autoproxyresponse/index.js:18:7)
    at runMiddlewares (/var/task/node_modules/@middy/core/index.js:119:88)
    at runRequest (/var/task/node_modules/@middy/core/index.js:88:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I'm aware it is a 3-rd party plugin however maybe someone could tell me: **is there an "official" plugin that does the same job?** Or how to fix that plugin?

The whole plugin's code is as following:
```
exports.autoProxyResponse = function() {
  return {
    after: function(handler, next) {
      if (!handler.response) {
        // Default response is empty object
        handler.response = {}
      }
      if (!handler.response.statusCode) {
        // Convert basic object to LAMBDA_PROXY response
        const body = JSON.stringify(handler.response)
        handler.response = {}
        handler.response.statusCode = 200
        handler.response.headers = {
          'Content-Type': 'application/json',
        }
        handler.response.body = body
      }
      next()
    },
    onError: function(_handler, next) {
      next()
    }
  }
}
```

Unfortunately, it is not on the GitHub, so it's hard to request a fix. It's only on npm https://www.npmjs.com/package/middy-autoproxyresponse

**Comment by serverlesspolska** [comment]
Strange thing, I removed that lib from the code and it still works as expected 🤔

I'm also using those middlewares
```
const middy = require('@middy/core')
const validator = require('@middy/validator')
const httpJsonBodyParser = require('@middy/http-json-body-parser')
const httpErrorHandler = require('@middy/http-error-handler')

const handler = async (event) => {
  [...]
  const myObject = { 
     field: 'value'
  }
  return myObject
}

const inputSchema = {
[...]
}

module.exports.handler = middy(handler)
  .use(httpJsonBodyParser())
  .use(validator({ inputSchema }))
  .use(httpErrorHandler())
```
So which of those plugins does a conversion from JavaScript literal into the object expected by AWS API Gateway? Similra to the following structure?
```
{
  statusCode: 200,
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    hello: 'world'
  })
}
```

Is it `@middy/http-error-handler`?

**Comment by willfarrell** [comment]
In v2 the use of callbacks was deprecated. You can check out the response serializer middleware or write your own, it looks pretty simple.
