### ISSUE TITLE
7.0.2: could not find declaration for executionModeStreamifyResponse

### ISSUE THREAD

**Issue by mdesousa** [middyjs/middy#1554]
after upgrading from 6.x to 7.0.2 and following the [instructions to migrate](https://middy.js.org/docs/upgrade/6-7) (we use streamifyResponse) we are getting the error below during the build:

```
src/index.ts:3:65 - error TS7016: Could not find a declaration file for module '@middy/core/StreamifyResponse'. '/MyProject/packages/lambda/node_modules/@middy/core/executionModeStreamifyResponse.js' implicitly has an 'any' type.
  If the '@middy/core' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module '@middy/core/StreamifyResponse';`
```

looking at the files distributed in the package, it seems to be missing `executionModeStreamifyResponse.d.ts`

**Comment by willfarrell** [comment]
We currently have the types here: https://github.com/middyjs/middy/blob/main/packages/core/index.d.ts#L15

If these need to be moved and updated, a PR is most welcome.
