### ISSUE TITLE
Lost support for CJS in 3.2.0

### ISSUE THREAD

**Issue by nicko-winner** [middyjs/middy#891]
**Describe the bug**
CJS imports stopped working in 3.2.0, but it works in 3.1.0

**To Reproduce**
How to reproduce the behavior:
```
const middy = require('@middy/core');
middy().handler(...);
// middy is not a function. 
```
**Expected behavior**
Would expect a major version bump if CJS support is dropped.

**Environment (please complete the following information):**
 - Node.js: [e.g. 14.x]
 - Middy: [e.g. 3.2.0]

**Comment by willfarrell** [comment]
See https://github.com/middyjs/middy/pull/890, build dependency fix a bug that we depended upon. Does it work in 3.2.2?

**Comment by nicko-winner** [comment]
3.2.2 resolved it, thanks!
