### PR TITLE
fix(types): typescript compile error

### LINKED ISSUE #1176: TypeScript compile error in @middy/core 5.2.4
**Describe the bug**
After updating @middy/core from 5.2.3 to 5.2.4, an error occurred in TypeScript compile (tsc).

**To Reproduce**
How to reproduce the behaviour:

Sample code 

- packages/server/src/lambda/handlers/api-gateway/rest-api/router.ts

```ts
import serverlessExpress from "@codegenie/serverless-express";
import middy from "@middy/core";
import express from "express";

const app = express();

export const handler = middy(serverlessExpress({ app }));
```

Thrown error

```shell
tsc --noEmit

src/lambda/handlers/api-gateway/rest-api/router.ts:11:30 - error TS2345: Argument of type 'Handler<any, any> & ConfigureResult<any, any>' is not assignable to parameter of type 'PluginObject | MiddyInputHandler<any, any, Context> | undefined'.
  Type 'Handler<any, any> & ConfigureResult<any, any>' is not assignable to type 'MiddyInputHandler<any, any, Context>'.
    Types of parameters 'callback' and 'opts' are incompatible.
      Type 'MiddyHandlerObject' is not assignable to type 'Callback<any>'.
        Type 'MiddyHandlerObject' provides no match for the signature '(error?: string | Error | null | undefined, result?: any): void'.

11 export const handler = middy(serverlessExpress({ app }));
```

**Expected behaviour**
tsc can run without errors.

**Environment (please complete the following information):**

- Node.js: 20.9.0
- Middy: 5.2.4
- AWS SDK 2.1450.0

### PR DESCRIPTION
**Pull request by lmammino**
This should fix #1176.

I am not entirely sure this won't cause other weird typing side effects, so I'd love it if someone with some TypeScript expertise could do a thorough review.

CC @naorpeled

### CODE REVIEW

File: packages/core/index.d.ts [hunk 1]
```diff
@@ -168,6 +168,7 @@ declare function middy<
   TInternal extends Record<string, unknown> = {}
 > (
   handler?:
+  | LambdaHandler<TEvent, TResult>
```
Comment (tonivdv) [inline packages/core/index.d.ts:171]: Seems to solve the typing issue indeed ...

**Review by naorpeled — APPROVED** [review]

**Comment by naorpeled** [comment]
Hey @lmammino,
sorry for the huge delay.
Looks good to me.
