### ISSUE TITLE
v4 branch gives ESM/CommonJS error in CJS Typescript even though 4->5 doc says v4 supports CJS

### ISSUE THREAD

**Issue by RichardBradley** [middyjs/middy#1235]
**Describe the bug**

Sorry if this is due to my misunderstanding. 
I'm trying to use middy in a Typescript project that is using CommonJS.
The notes at https://middy.js.org/docs/upgrade/4-5 say " v4.x is super stable and support CJS."

This project was working with Middy 3

**To Reproduce**

I'm on Node18 in AWS Lambda

My tsconfig looks like this:
```
{
  "compilerOptions": {
    "lib": ["es2023"],
    "module": "node16",
    "moduleResolution": "node16",
    "esModuleInterop": true,
    "isolatedModules": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "es2022",
    "strict": true,
    "outDir": "lib",
    "strictNullChecks": true
  },
```

My package.json looks like:

```
{
  "dependencies": {
    "@middy/core": "^4.6.5",
    "@middy/http-error-handler": "^4.6.5",
    "@middy/http-json-body-parser": "^4.6.5",
    "@middy/sqs-json-body-parser": "^2.5.7",
```

My code like:

```
import middy from "@middy/core";

export const withErrorHandling = (handler: Handler) =>
    middy(handler)
        .use(errorHandler())
        .use(httpErrorHandler());
```

But I get the following error from tsc:

```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@middy/core")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to 'C:/work/cabinet-office/ierds/middle-tier/erop-api/package.json'.

3 import middy from "@middy/core";
```

I did try converting my project to ESM but it was disruptive and broke some other things that I couldn't fix.

The other suggestion from the compiler is to use a dynamic import, but that returns a Promise, which would be very disruptive to my code, as all my function definitions that build on middy would then instead be a Promise of a function. Do I really need to do that?

How can I use Middy v4 in CommonJS mode?

Many thanks,

Rich

**Environment (please complete the following information):**

- Node.js: 18
- Middy: 4.6.5
- AWS SDK 3.624.0

**Comment by willfarrell** [comment]
I can't say I've heard of others running into this issue when migrating to v4, v5 yes, but not v4. Generally these errors are related the tsconfig file. tsconfigs are not where the specialties are, sorry I can't be more help here.

On a related note, nodejs 20 added in --experimental-require-module flag that may help in this case. Middy v6 will support this new flag, an alpha is planned for release soon. Ref: #1233

**Comment by RichardBradley** [comment]
Do you have an example of a typescript project using v4 in CJS mode that works, please?

**Comment by willfarrell** [comment]
The only tsconfig I know that works it this one: https://middy.js.org/docs/intro/typescript

**Comment by RichardBradley** [comment]
Looks to me like that's a ESM module build, rather than CJS

**Comment by wshivers93** [comment]
I'm also seeing this issue. Upgraded to version 4.x because I don't currently have the ability to migrate our whole app to ESM.

The tsconfig setting causing the problem is `moduleResolution`. If you have that set to `node16` per Typescript's recommendation, the compiler thinks @middy/core is an ESM module instead of a commonJS module.

As a workaround, setting `moduleResolution` to `node` allows the project to build successfully.

```
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "compilerOptions": {
    ...
    "moduleResolution": "node",
    "module": "commonjs",
    ... 
  }
}
```

**Comment by willfarrell** [comment]
@wshivers93 thanks for sharing. Closing, because there is now a workaround.
