### ISSUE TITLE
Export default causing 'default' is not a function error

### ISSUE THREAD

**Issue by sssanwar** [middyjs/middy#964]
https://github.com/middyjs/middy/blob/dff8f30065dc303b9bbcdb7f1e8ee9af98aadafe/packages/core/index.js#L11

Is it possible to add `export` to the line such as `export const middy = ...` ?

The reason is I use middy for a lambda service that is written as an AWS CDK construct library (https://github.com/projen/projen/blob/main/docs/awscdk-construct.md), and the construct makes use of JSII compiler that prevents me from setting `esModuleInterop` in tsconfig to true. I am getting the error message like: middy.default is not a function.

The same would apply to the middleware packages.

Using default to export is a bad practice anyway:
https://basarat.gitbook.io/typescript/main-1/defaultisbad

**Comment by sssanwar** [comment]
Adding `export` before `const` should be backward compatible. The existing `export default` line at the bottom can be kept for backward compatibility.

**Comment by willfarrell** [comment]
All packages only have a single export (excluding `util`) and always will. This is by design for ease of use. This TypeScript "best practice" list you shared seems really nit picky and I 'm not seeing the value add for the amount of additional maintenance work that will be required long term. It seems like a small change, but it has ripples through testing and the documentation that will take significantly more time.

It sounds like AWS CDK is transpiling to CommonJS then bundling for some reason, which seems to be the root of your issue and a long running known issue. It should bundle using tree-shaking first, then transpile. Try `esbuild` instead.

ESM is supported in the nodejs14.x runtime. Shipping ESM (.mjs) reduces build times, cold start times, and is a smaller bundle size. Easy win to put on your annual performance review. Note: I'm considering dropping cjs support next year.

**Comment by sssanwar** [comment]
As mentioned before, the AWS CDK construct project type does not allow overriding the tsconfig. I'm not allowed to change the output target to ESM. It's already using `esbuild`. The projen AWS CDK construct template is a standard tool developed by AWS. So to learn that you refuse to accomodate this is kinda disheartening. The best practice is not only a TS thing - it applies to JS too. Just google 'export default is bad'. If that's nick picky, by the same logic, all best practices should sound nit picky to you too. 

> I 'm not seeing the value add for the amount of additional maintenance work that will be required long term. It seems like a small change, but it has ripples through testing and the documentation that will take significantly more time.
I cloned the repo and added `export` statements as mentioned. Everything still compiles and passes the tests. So not sure where that's coming from. As said, it is backward compatible.

**Comment by willfarrell** [comment]
Glad to hear your workaround meets your needs. AWS CDK allowing the override of tsconfig sounds like useful feature others might benefit from. I would encourage your to open an issue or submit a PR to their project to have it included.

PS Keep in mind that AWS project typically follow the runtime deprecation cycle while Middy follows the runtime release cycle (latest 2 only). Older versions of Middy may be more appropriate when integrating with AWS CDK, Powertools, etc.
